### ISSUE TITLE
Failed to read values from vcontrold

### ISSUE THREAD

**Issue by winnieXY** [euweb/pyvclient#1]
Hello,
I'm failing to read values from vcontrold - it doesn't matter if it is a status or a temperature.

What should be changed to the pyvclient working. I'm sadly not captable of writing python.

See the backtrace below (with a status):
```
2021-05-02 12:58:40 raspberrypi pyvclient.vcomm.vcomm[20708] INFO process commands
2021-05-02 12:58:40 raspberrypi pyvclient.vcomm.vcomm[20708] INFO connect to vcontrold
2021-05-02 12:58:40 raspberrypi pyvclient.vcomm.vcomm[20708] INFO disconnect from vcontrold
2021-05-02 12:58:41 raspberrypi pyvclient.vcomm.vcomm[20708] INFO process commands
2021-05-02 12:58:41 raspberrypi pyvclient.vcomm.vcomm[20708] INFO connect to vcontrold
2021-05-02 12:58:41 raspberrypi pyvclient.vcomm.vcomm[20708] INFO disconnect from vcontrold
Traceback (most recent call last):
  File "/home/pi/.local/bin/pyvclient", line 10, in <module>
    sys.exit(main())
  File "/home/pi/.local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/pi/.local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pi/.local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/pyvclient/cli.py", line 31, in main
    pyvclient = PyVClient(vcomm, config)
  File "/home/pi/.local/lib/python3.7/site-packages/pyvclient/pyvclient.py", line 53, in __init__
    self.items = self._get_items()
  File "/home/pi/.local/lib/python3.7/site-packages/pyvclient/pyvclient.py", line 69, in _get_items
    values.get(commands[cmd])[0]))
  File "/home/pi/.local/lib/python3.7/site-packages/pyvclient/pyvclient.py", line 139, in parse_item
    data.value = self.parse_value(raw_value, data)
  File "/home/pi/.local/lib/python3.7/site-packages/pyvclient/pyvclient.py", line 99, in parse_value
    value = str(value).replace(item.unit, '').strip()
AttributeError: 'ObjectView' object has no attribute 'unit'
```

vclient output:
```
vclient -h localhost -p 3002 -c WarmWasserAktiv
WarmWasserAktiv:
1
-----
vclient -h localhost -p 3002 -c TempWWIst
TempWWIst:
128.500000 °C
```
vcontrold is configured in this way:
vito.xml:
```
 <command name='WarmWasserAktiv' protocmd='getaddr'>
                        <addr>2320</addr>
                        <len>1</len>
                        <unit>BA</unit>
                        <description>Betriebsart</description>
 </command>
 <command name='TempWWIst' protocmd='getaddr'>
                        <addr>0812</addr>
                        <len>2</len>
                        <unit>TD</unit>
                        <description>Speichertemperatur in °C</description>
  </command>
```
vcontrold.xml:
```
               <unit name='Betriebsart'>
                        <abbrev>BA</abbrev>
                        <type>enum</type>
                        <enum bytes='00' text='0'/>
                        <enum bytes='01' text='1'/>
                        <enum bytes='02' text='2'/>
                        <enum bytes='03' text='3'/>
                        <enum bytes='04' text='4'/>
                        <!--<enum bytes='00' text='Abschaltbetrieb'/>
                        <enum bytes='01' text='Nur Warmwasser'/>
                        <enum bytes='02' text='Heizen und Warmwasser'/>
                        <enum bytes='03' text='Dauernd red. Betrieb'/>
                        <enum bytes='04' text='Dauernd Normalbetrieb'/>-->
                        <enum text='?'/>
                </unit>

                <unit name='Temperatur'>
                        <abbrev>TD</abbrev>
                        <calc get='V/10' set='V*10'/>
                        <type>short</type>
                        <entity>°C</entity>
                </unit>
```

**Comment by winnieXY** [comment]
I forgot the relevant snipplet from the pyvclient configuration. The rest of the configuration file is left as is (e.g. precision)
```
Properties:
   TempKesselIst:
     readonly: true
     interval: 300
   WarmWasserAktiv:
     readonly: false
     interval: 3600
```

**Comment by winnieXY** [comment]
This issue can be closed. The Properties needs to be named "getTempKesselIst" or "getWarmWasserAktiv"/"setWarmWasserAktiv"
